name: BuildImageToECR

on: push

jobs:

    build-to-dockerhub:
       runs-on: ubuntu-latest

       steps:

       - name: Code Checkout
         uses: actions/checkout@v4.1.7

       - name: Login to AWS
         uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.ACCESS_KEY }}
           aws-secret-access-key: ${{ secrets.SECRET_KEY }}
           aws-region: ${{ secrets.REGION }}


    build-to-ecr:
       runs-on: ubuntu-latest

       steps:

       - name: Code Checkout
         uses: actions/checkout@v4.1.7

       - name: Login to ECR
         uses: docker/login-action@v3.3.0

         with:
           registry: public.ecr.aws
           username: ${{ secrets.ACCESS_KEY }}
           password: ${{ secrets.SECRET_KEY }}
         env:
           aws-region: ${{ secrets.REGION }}
         
