name: Docker Build
on: workflow_dispatch
jobs:
    Build-To-Dockerhub:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4.1.7
      
            - name: Docker Login
              uses: docker/login-action@v3.3.0
              with: 
                  Username: ${{ secrets.DOCKERHUB_USERNAME }}
                  Password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Build Image
              run: |
                  printenv
                  docker build -t javanta:latest .
                  docker tag javanta:latest faozio/ichigo:${GITHUB_RUN_NUMBER}
                  docker push faozio/ichigo:${GITHUB_RUN_NUMBER}
