name: ECR Public Build
on: workflow_dispatch
jobs:
    Build-To-PublicECR:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4.1.7
      
            - name: ECR Login
              uses: docker/login-action@v3.3.0
              with: 
                  registry: public.ecr.aws
                  Username: ${{ secrets.ACCESS_USERNAME }}
                  Password: ${{ secrets.ACCESS_PASSWORD }}
              env:
                    aws-region: ${{  secrets.REGION  }}
            - name: Build Image
              run: |
                  printenv
                  docker build -t javanta:latest .
                  docker tag javanta:latest public.ecr.aws/d8c0k3y2/faozio:${GITHUB_RUN_NUMBER}
                  docker push public.ecr.aws/d8c0k3y2/faozio:${GITHUB_RUN_NUMBER}

