name: Docker Build
on: push
jobs:
    Build-To-Dockerhub:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4.1.7
      
            - name: Docker Login
              uses: docker/login-action@v3.3.0
              with: 
                  Username: ${{ secrets.DOCKERHUB_USERNAME }}
                  Password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Build Image
              run: |
                  docker build -t javanta:latest .
                  docker tag javanta:latest faozio/ichigo:v1
                  docker push faozio/ichigo:v1
